
---
- name: Create Hawkular download tmp directory
  file: path="{{hawkular_download_tmpdir}}" state=directory

- name: Download Hawkular WildFly Agent installer

  # Can't use due to bug: https://github.com/ansible/ansible-modules-core/issues/2166
  #uri:
  #  url="{{hawkular_server_url}}/hawkular/wildfly-agent/installer"
  #  dest="{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar"
  #  user="{{hawkular_server_url_username}}"
  #  password="{{hawkular_server_url_password}}"
  #  force_basic_auth=true
  #  method=POST
  #  body=""
  #  follow_redirects=all
  #  validate_certs=no

  shell:
    "curl --silent --show-error --create-dirs --user '{{hawkular_server_url_username}}:{{hawkular_server_url_password}}' --output '{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar' {{hawkular_server_url}}/hawkular/wildfly-agent/installer"

- name: Run the Hawkular WildFly Agent installer
  command:
    "java -jar {{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar
      --username={{hawkular_wildfly_agent_username}}
      --password={{hawkular_wildfly_agent_password}}
      --target-location={{wildfly_install_dir}}/{{wildfly_distro_root_dir}}
      --server-url={{hawkular_server_url}}
      --feed-id={{hawkular_wildfly_agent_feed_id}}"

- name: Remove the Hawkular WildFly Agent installer
  file: path="{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar" state=absent

