
---
- name: Generate Temporary Encryption Key
  shell: "tr -cd '0-9a-z' < /dev/urandom | head -c 30; echo"
  register: hawkular_tmp_encryption_key

- name: Create Hawkular download tmp directory
  file: path="{{hawkular_download_tmpdir}}" state=directory

- name: Download Hawkular WildFly Agent installer

  # Can't use due to bug: https://github.com/ansible/ansible-modules-core/issues/2166
  #uri:
  #  url="{{hawkular_server_url}}/hawkular/wildfly-agent/installer"
  #  dest="{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar"
  #  user="{{hawkular_server_url_username}}"
  #  password="{{hawkular_server_url_password}}"
  #  force_basic_auth=true
  #  method=POST
  #  body="username={{hawkular_wildfly_agent_username}}&password={{hawkular_wildfly_agent_password}}&encryption-key={{hawkular_tmp_encryption_key.stdout}}"
  #  follow_redirects=all
  #  validate_certs=no

  shell:
    "curl --silent --show-error --create-dirs --user '{{hawkular_server_url_username}}:{{hawkular_server_url_password}}' --output '{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar' --data 'username={{hawkular_wildfly_agent_username}}&password={{hawkular_wildfly_agent_password}}&encryption-key={{hawkular_tmp_encryption_key.stdout}}' {{hawkular_server_url}}/hawkular/wildfly-agent/installer"

- name: Run the Hawkular WildFly Agent installer
  command:
    "java -jar {{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar
      --encryption-key={{hawkular_tmp_encryption_key.stdout}}
      --target-location={{wildfly_install_dir}}/wildfly-{{wildfly_version}}
      --server-url={{hawkular_server_url}}
      --feed-id={{ansible_default_ipv4.address}}"

- name: Remove the Hawkular WildFly Agent installer
  file: path="{{hawkular_download_tmpdir}}/hawkular-wildfly-agent-installer.jar" state=absent

