- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  tasks:

  - set_fact:
      is_k8s: true
      kiali_vars:
        deployment:
          view_only_mode: false
          accessible_namespaces:
          - test1
          - test2
          - test3
          - test4
          - test5
          - test6
          - test7
          - test8
          - test9
          - test10
          - test11
          - test12
          - test13
          - test14
          - test15
          - test16
          - test17
          - test18
          - test19
          - test20
          - test21
          - test22
          - test23
          - test24
          - test25
          - test26
          - test27
          - test28
          - test29
          - test30
          - test31
          - test32
          - test33
          - test34
          - test35
          - test36
          - test37
          - test38
          - test39
          - test40
          - test41
          - test42
          - test43
          - test44
          - test45
          - test46
          - test47
          - test48
          - test49
          - test50

  - debug:
      msg: "MAZZ START: {{ kiali_vars }}"

  - name: Create additional Kiali roles on all accessible namespaces on Kubernetes
    vars:
      role_namespaces: "{{ kiali_vars.deployment.accessible_namespaces }}"
    k8s:
      definition: "{{ lookup('template', 'templates/kubernetes/' + ('role-viewer' if kiali_vars.deployment.view_only_mode|bool == True else 'role') + '.yaml') }}"
    when:
    - is_k8s == True
    - '"**" not in kiali_vars.deployment.accessible_namespaces'

  - name: Create additional Kiali role bindings on all accessible namespaces on Kubernetes
    vars:
      role_namespaces: "{{ kiali_vars.deployment.accessible_namespaces }}"
    k8s:
      definition: "{{ lookup('template', 'templates/kubernetes/rolebinding.yaml') }}"
    when:
    - is_k8s == True
    - '"**" not in kiali_vars.deployment.accessible_namespaces'
