- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  tasks:

  - set_fact:
      is_k8s: true
      kiali_vars:
        api:
          namespaces:
            label_selector: "kiali.io/member-of=istio-system"
        deployment:
          view_only_mode: false
          accessible_namespaces:
          - test1
          - test2
          - test3
          - test4
          - test5

  - debug:
      msg: "MAZZ START: {{ kiali_vars }}"

  - name: Create additional Kiali label on all accessible namespaces
    include_tasks: batch-labels/process-additional-namespace-label.yml
    vars:
      # everything to the left of the = is the label name; to the right is the label value
      the_namespace_label_name: "{{ kiali_vars.api.namespaces.label_selector | regex_replace('^(.*)=.*$', '\\1') }}"
      the_namespace_label_value: "{{ kiali_vars.api.namespaces.label_selector | regex_replace('^.*=(.*)$', '\\1') }}"
    loop: "{{ kiali_vars.deployment.accessible_namespaces | batch(lookup('env', 'NAMESPACE_BATCH_SIZE') | int | default(3, True)) | list }}"
    loop_control:
      loop_var: accessible_namespaces_batch
    when:
    - '"**" not in kiali_vars.deployment.accessible_namespaces'
