- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  tasks:

  - set_fact:
      is_k8s: true
      kiali_vars:
        deployment:
          view_only_mode: false
          accessible_namespaces:
          - test1
          - test2
          - test3
          - test4
          - test5

  - debug:
      msg: "MAZZ START: {{ kiali_vars }}"

  - name: Create additional Kiali roles on all accessible namespaces on Kubernetes
    include_tasks: batch-roles/process-additional-roles.yml
    vars:
      the_cluster_type: "kubernetes"
    loop: "{{ kiali_vars.deployment.accessible_namespaces | batch(lookup('env', 'NAMESPACE_BATCH_SIZE') | int | default(3, True)) | list }}"
    loop_control:
      loop_var: accessible_namespaces_batch
    when:
    - is_k8s == True
    - '"**" not in kiali_vars.deployment.accessible_namespaces'
