- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  tasks:

  - set_fact:
      is_k8s: true
      kiali_vars:
        deployment:
          view_only_mode: false
          accessible_namespaces:
          - test1
          - test2

  - debug:
      msg: "MAZZ START: {{ kiali_vars }}"

  - name: Build additional Kiali roles yaml on Kubernetes
    include_tasks: build-additional-roles-yaml.yml
    vars:
      process_resource_cluster: "kubernetes"
    loop: "{{ kiali_vars.deployment.accessible_namespaces }}"
    loop_control:
      loop_var: role_namespace
    when:
    - is_k8s == True
    - '"**" not in kiali_vars.deployment.accessible_namespaces'

  - name: Create additional Kiali roles on Kubernetes
    k8s:
      state: "present"
      definition: "{{ all_additional_roles_yaml }}"
    when:
    - is_k8s == True

  - name: Erase potentially large fact
    set_fact:
      all_additional_roles_yaml: {}
