
---
- name: Create WildFly install directory
  file: path="{{wildfly_install_dir}}" state=directory mode=0755

- name: Unpack WildFly into its installation directory
  unarchive:
    src="{{wildfly_download_tmpdir}}/{{wildfly_distro_filename}}"
    dest="{{wildfly_install_dir}}"
